version: '3'

services:
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - /Users/mina/Documents/HR105/Docker-Compose-Proxy/ReviewService/database/:/docker-entrypoint-initdb.d
      - ./../database:/var/lib/mysql:rw,delegated

  review-servise:
    build: .
    depends_on:
      - 'database'
    ports:
      - '3003:3003'
    restart: always
    
    


